In [40]:
# import libraries
import pandas as pd
import numpy as np


# import dataset
df = pd.read_csv("sylvester.csv")

# find determinant function
def dtr(mat1):
    
    size = mat1.shape[0]
    
    if(size == 1): 
        return mat1[0,0]
    
    mat = mat1[0]
    
    summ = 0;
    for i in range(size):
        newmat = np.delete(mat1, 0, 0)
        newmat = np.delete(newmat, i, 1)
        
        summ += (-1)**i * mat[i] * dtr(newmat)
        dtr(newmat)
        
    return summ

# sylvester criterion function
def isPositiveDef(df):
    size = df.shape[0]
    valid = 1
    for i in range(1,size+1):
        mat = np.array(df.iloc[0:i,0:i].values)
        val = dtr(mat)
        
        if(val<0):
            valid = -1
            break
        elif val==0:
            valid = 0
    
    return valid


# sylvester criterion fn call
strr = isPositiveDef(df)


# print matrix
print(df.values, "\n")

# print result
if strr==0:
    print("Positive Semi Definite")
elif strr==1:
    print("Positive Definite")
else:
    print("Not Positive Definite")


[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]] 

Positive Definite
